// Generated by CoffeeScript 1.7.1
(function() {
  var TodoView, TodosChildrenView, TodosFooterView, Widget,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __slice = [].slice,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Widget = (function() {
    function Widget() {
      var children, data;
      data = arguments[0], children = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      this.data = data;
      this.children = children;
      this.update = __bind(this.update, this);
      this.isWidget = true;
      this.initialize();
    }

    Widget.prototype.initialize = function() {};

    Widget.prototype.process = function() {
      var callback, result, self;
      self = this;
      result = this.template();
      callback = function(el) {
        return self.el = el;
      };
      if (result[1] && typeof result[1] === "object" && (!(result[1] instanceof Array))) {
        if (result[1].afterRender) {
          result[1].afterRender.unshift(callback);
        } else {
          result[1].afterRender = callback;
        }
      } else {
        result.splice(1, 0, {
          afterRender: callback
        });
      }
      return result;
    };

    Widget.prototype.update = function() {
      return T(this.process()).render({
        replace: this.el
      });
    };

    Widget.prototype.render = function() {
      var args, _ref;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = T(this.process())).render.apply(_ref, args);
    };

    Widget.create = function(props) {
      var Child, k, v;
      Child = (function(_super) {
        __extends(Child, _super);

        function Child() {
          return Child.__super__.constructor.apply(this, arguments);
        }

        return Child;

      })(this);
      for (k in props) {
        v = props[k];
        Child.prototype[k] = v;
      }
      return function() {
        var children, data;
        data = arguments[0], children = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
        return (function(func, args, ctor) {
          ctor.prototype = func.prototype;
          var child = new ctor, result = func.apply(child, args);
          return Object(result) === result ? result : child;
        })(Child, [data].concat(__slice.call(children)), function(){});
      };
    };

    Widget.inline = function(data, widgetProps) {
      return this.create(widgetProps)(data).process();
    };

    return Widget;

  })();

  this.TodosView2 = Widget.create({
    template: function() {
      var self;
      self = this;
      return [
        'header#header', ['h1', 'todos'], [
          'input#new-todo', {
            type: 'text',
            placeholder: 'What needs to be done?',
            autofocus: 'autofocus',
            keyup: function(e) {
              var el;
              el = $(this);
              if (e.which === ENTER_KEY && el.val().trim()) {
                self.data.todos.push(new Todo(self.data.todos, el.val().trim()));
                return el.val('');
              }
            }
          }
        ], [
          'section#main', [
            'input#toggle-all', {
              type: 'checkbox',
              click: function() {
                return self.data.todos.toggleAllCompleted($(this).is(':checked'));
              }
            }
          ], [
            'label', {
              "for": 'toggle-all'
            }, 'Mark all as complete'
          ], TodosChildrenView({
            todos: this.data.todos,
            filter: this.data.filter
          }).process()
        ], TodosFooterView({
          todos: this.data.todos,
          filter: this.data.filter
        }).process()
      ];
    }
  });

  TodosChildrenView = Widget.create({
    initialize: function() {
      this.data.todos.subscribe(CHANGED, this.update);
      return Busbup.subscribe(FILTER, (function(_this) {
        return function(_, filter) {
          _this.data.filter = filter;
          return _this.update();
        };
      })(this));
    },
    template: function() {
      var todo;
      return [
        'ul#todo-list', (function() {
          var _i, _len, _ref, _results;
          _ref = this.data.todos.children();
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            todo = _ref[_i];
            if ((this.data.filter === 'active' && todo.completed) || (this.data.filter === 'completed' && !todo.completed)) {
              continue;
            }
            _results.push(TodoView({
              todos: this.data.todos,
              todo: todo
            }).process());
          }
          return _results;
        }).call(this)
      ];
    }
  });

  TodoView = Widget.create({
    initialize: function() {
      return this.data.todo.subscribe(CHANGED, this.update);
    },
    close: function() {
      var trimmedValue;
      if (!this.el.hasClass('editing')) {
        return;
      }
      this.el.removeClass('editing');
      if (trimmedValue = this.input.val().trim()) {
        return this.data.todo.title = trimmedValue;
      }
    },
    template: function() {
      var self;
      self = this;
      return [
        'li', this.data.todo.completed ? {
          "class": 'completed'
        } : void 0, [
          '.view', {
            dblclick: function() {
              self.el.addClass('editing');
              return self.input.focus();
            }
          }, [
            "input.toggle", {
              type: 'checkbox',
              checked: (this.data.todo.completed ? 'checked' : void 0),
              click: function() {
                return self.data.todo.completed = !self.data.todo.completed;
              }
            }
          ], ['label', this.data.todo.title], [
            'button.destroy', {
              click: function() {
                return self.data.todos.splice(self.data.todos.indexOf(self.data.todo), 1);
              }
            }
          ]
        ], [
          'input.edit', {
            afterRender: function(el) {
              return self.input = $(el);
            },
            type: 'text',
            keypress: function(e) {
              if (e.which === ENTER_KEY) {
                return self.close();
              }
            },
            keydown: function(e) {
              if (e.which === ESC_KEY) {
                $(this).val(self.data.todo.title);
                return self.el.removeClass('editing');
              }
            },
            blur: function() {
              return self.close();
            }
          }
        ]
      ];
    }
  });

  TodosFooterView = Widget.create({
    initialize: function() {
      this.data.todos.subscribe(CHANGED, this.update);
      return Busbup.subscribe(FILTER, (function(_this) {
        return function(_, filter) {
          return _this.data.filter = filter;
        };
      })(this));
    },
    filters: function() {
      return [
        {
          name: 'all',
          label: 'All',
          selected: this.data.filter === 'all'
        }, {
          name: 'active',
          label: 'Active',
          selected: this.data.filter === 'active'
        }, {
          name: 'completed',
          label: 'Completed',
          selected: this.data.filter === 'completed'
        }
      ];
    },
    template: function() {
      var filter, self;
      self = this;
      return [
        'footer#footer', this.data.todos.length() === 0 ? {
          style: {
            display: 'none'
          }
        } : void 0, [
          'span#todo-count', ['strong', this.data.todos.remaining()], " item", [
            'span.plural', this.data.todos.remaining() <= 1 ? {
              style: {
                display: 'none'
              }
            } : void 0, 's'
          ], " left"
        ], [
          'ul#filters', (function() {
            var _i, _len, _ref, _results;
            _ref = this.filters();
            _results = [];
            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
              filter = _ref[_i];
              _results.push(Widget.inline(filter, {
                initialize: function() {
                  return Busbup.subscribe(FILTER, (function(_this) {
                    return function(_, filter) {
                      _this.data.selected = filter === _this.data.name;
                      return _this.update();
                    };
                  })(this));
                },
                template: function() {
                  return [
                    "li." + this.data.name, [
                      "a", this.data.selected ? {
                        "class": 'selected'
                      } : void 0, {
                        href: "#/" + this.data.name
                      }, this.data.label
                    ]
                  ];
                }
              }));
            }
            return _results;
          }).call(this)
        ], [
          'button#clear-completed', this.data.todos.completed() === 0 ? {
            style: {
              display: 'none'
            }
          } : void 0, {
            click: function() {
              return self.data.todos.clearCompleted();
            }
          }, ['span', 'Clear completed (', ['span.completed-value', this.data.todos.completed()], ')']
        ]
      ];
    }
  });

}).call(this);
