// Generated by CoffeeScript 1.7.1
(function() {
  var TodosChildrenView,
    __slice = [].slice;

  this.TodosView = (function() {
    function TodosView(todos) {
      this.todos = todos;
      console.log('TodosView.constructor');
    }

    TodosView.prototype.process = function() {
      return [
        'header#header', ['h1', 'todos'], [
          'input#new-todo', {
            type: 'text',
            placeholder: 'What needs to be done?',
            autofocus: 'autofocus',
            keyup: function(e) {
              var el;
              el = $(this);
              if (e.which === ENTER_KEY && el.val().trim()) {
                self.todos.push(new Todo(self.todos, el.val().trim()));
                return el.val('');
              }
            }
          }
        ], [
          'section#main', [
            'input#toggle-all', {
              type: 'checkbox',
              click: function() {
                return self.todos.toggleAllCompleted($(this).is(':checked'));
              }
            }
          ], [
            'label', {
              "for": 'toggle-all'
            }, 'Mark all as complete'
          ], new TodosChildrenView(this.todos).process()
        ], new TodosFooterView(this.todos).process()
      ];
    };

    TodosView.prototype.render = function() {
      var args, _ref;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      return (_ref = T(this.process())).render.apply(_ref, args);
    };

    return TodosView;

  })();

  TodosChildrenView = (function() {
    function TodosChildrenView(todos) {
      this.todos = todos;
      this.todos.subscribe(CHANGED, (function(_this) {
        return function() {
          return T(_this.process()).render({
            replace: _this.el
          });
        };
      })(this));
      Busbup.subscribe(FILTER, (function(_this) {
        return function() {
          return T(_this.process()).render({
            replace: _this.el
          });
        };
      })(this));
    }

    TodosChildrenView.prototype.process = function() {
      var self, todo;
      self = this;
      return [
        'ul#todo-list', {
          afterRender: function(el) {
            return self.el = $(el);
          }
        }, (function() {
          var _i, _len, _ref, _results;
          _ref = this.todos.children();
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            todo = _ref[_i];
            if ((window.filter === 'active' && todo.completed) || (window.filter === 'completed' && !todo.completed)) {
              continue;
            }
            _results.push(new TodoView(this.todos, todo).process());
          }
          return _results;
        }).call(this)
      ];
    };

    return TodosChildrenView;

  })();

  this.TodosFooterView = (function() {
    function TodosFooterView(todos) {
      this.todos = todos;
      this.todos.subscribe(CHANGED, (function(_this) {
        return function() {
          return T(_this.process()).render({
            replace: _this.el
          });
        };
      })(this));
      Busbup.subscribe(FILTER, (function(_this) {
        return function() {
          return _this.setFilter(window.filter);
        };
      })(this));
    }

    TodosFooterView.prototype.setFilter = function(filter) {
      this.el.find('#filters li a').removeClass('selected');
      return this.el.find("li." + filter + " a").addClass('selected');
    };

    TodosFooterView.prototype.process = function() {
      var self;
      self = this;
      return [
        'footer#footer', {
          afterRender: function(el) {
            self.el = $(el);
            return self.setFilter(window.filter);
          }
        }, this.todos.length() === 0 ? {
          style: {
            display: 'none'
          }
        } : void 0, [
          'span#todo-count', ['strong', this.todos.remaining()], " item", [
            'span.plural', this.todos.remaining() <= 1 ? {
              style: {
                display: 'none'
              }
            } : void 0, 's'
          ], " left"
        ], [
          'ul#filters', [
            'li.all', [
              'a', {
                href: '#/'
              }, 'All'
            ]
          ], [
            'li.active', [
              'a', {
                href: '#/active'
              }, 'Active'
            ]
          ], [
            'li.completed', [
              'a', {
                href: '#/completed'
              }, 'Completed'
            ]
          ]
        ], [
          'button#clear-completed', this.todos.completed() === 0 ? {
            style: {
              display: 'none'
            }
          } : void 0, {
            click: function() {
              return self.todos.clearCompleted();
            }
          }, ['span', 'Clear completed (', ['span.completed-value', this.todos.completed()], ')']
        ]
      ];
    };

    return TodosFooterView;

  })();

}).call(this);
