// Generated by CoffeeScript 1.7.1
(function() {
  this.TodoView = (function() {
    function TodoView(todos, todo) {
      this.todos = todos;
      this.todo = todo;
    }

    TodoView.prototype.close = function() {
      var trimmedValue;
      if (!this.el.hasClass('editing')) {
        return;
      }
      this.el.removeClass('editing');
      if (trimmedValue = this.input.val().trim()) {
        return this.todo.title = trimmedValue;
      }
    };

    TodoView.prototype.process = function() {
      var self;
      self = this;
      return [
        'li', {
          afterRender: function(el) {
            self.el = $(el);
            self.el.find('label').html(self.todo.title);
            self.el.toggleClass('completed', self.todo.completed);
            return self.el.find('.toggle').attr('checked', self.todo.completed);
          }
        }, [
          '.view', {
            dblclick: function() {
              self.el.addClass('editing');
              return self.input.focus();
            }
          }, [
            'input.toggle', {
              type: 'checkbox',
              click: function() {
                return self.todo.completed = !self.todo.completed;
              }
            }
          ], ['label', this.title], [
            'button.destroy', {
              click: function() {
                return self.todos.splice(self.todos.indexOf(self.todo), 1);
              }
            }
          ]
        ], [
          'input.edit', {
            afterRender: function(el) {
              return self.input = $(el);
            },
            type: 'text',
            keypress: function(e) {
              if (e.which === ENTER_KEY) {
                return self.close();
              }
            },
            keydown: function(e) {
              if (e.which === ESC_KEY) {
                $(this).val(self.todo.title);
                return self.el.removeClass('editing');
              }
            },
            blur: function() {
              return self.close();
            }
          }
        ]
      ];
    };

    return TodoView;

  })();

}).call(this);
