// Generated by CoffeeScript 1.7.1
(function() {
  var router, todosView;

  this.todos = TodosResource.load('todos');

  todosView = new TodosView(this.todos);

  todosView.render({
    inside: '#todoapp'
  });

  watch(this, 'todos', function() {
    TodosResource.save('todos', todos);
    return todosView.updateUI();
  });

  router = new routes();

  router.get('/', function() {
    return todosView.filterBy('all');
  });

  router.get('/:filter', function(req) {
    return todosView.filterBy(req.params.filter);
  });

}).call(this);
