// Generated by CoffeeScript 1.7.1
(function() {
  var router, todos;

  this.ENTER_KEY = 13;

  this.ESC_KEY = 27;

  this.todos = todos = TodosResource.load('todos');

  T(this.todos.render()).render({
    inside: '#todoapp'
  });

  watch(this, 'todos', function() {
    TodosResource.save('todos', todos);
    return todos.updateUI();
  });

  router = new routes();

  router.get('/', function() {
    return todos.filterBy('all');
  });

  router.get('/:filter', function(req) {
    return todos.filterBy(req.params.filter);
  });

  this.runThenWatch = function(obj, properties, callback) {
    callback();
    return watch(obj, properties, callback);
  };

}).call(this);
