// Generated by CoffeeScript 1.7.1
(function() {
  var router, todosView;

  this.todos = TodosResource.load('todos');

  watch(this, 'todos', (function() {
    return $.publish(TODOS_CHANGED);
  }), 1);

  $.subscribe(TODOS_CHANGED, function() {
    return TodosResource.save('todos', todos);
  });

  todosView = new TodosView(todos);

  todosView.render({
    inside: '#todoapp'
  });

  router = new routes();

  router.get('/', function() {
    return todosView.filterBy('all');
  });

  router.get('/:filter', function(req) {
    return todosView.filterBy(req.params.filter);
  });

}).call(this);
