// Generated by CoffeeScript 1.7.1
(function() {
  var o;

  this.ENTER_KEY = 13;

  this.ESC_KEY = 27;

  this.TODOS_CHANGED = 'todos_changed';

  this.runThenWatch = function(obj, properties, callback) {
    callback();
    return watch(obj, properties, callback);
  };

  o = $({});

  $.subscribe = function() {
    o.on.apply(o, arguments);
  };

  $.unsubscribe = function() {
    o.off.apply(o, arguments);
  };

  $.publish = function() {
    o.trigger.apply(o, arguments);
  };

}).call(this);
