// Generated by CoffeeScript 1.7.1
(function() {
  this.ENTER_KEY = 13;

  this.ESC_KEY = 27;

  this.runThenWatch = function(obj, properties, callback) {
    callback();
    return watch(obj, properties, callback);
  };

}).call(this);
