// Generated by CoffeeScript 1.7.1
(function() {
  this.Todo = (function() {
    function Todo(parent, title, completed) {
      var self;
      this.parent = parent;
      this.title = title;
      this.completed = completed;
      self = this;
      watch(this, 'title', function() {
        return self.el.find('label').html(self.title);
      });
      watch(this, 'completed', function() {
        return this.el.find('.toggle').attr('checked', this.completed);
      });
    }

    Todo.prototype.watchIgnore = ['parent', 'el', 'input'];

    Todo.prototype.close = function() {
      var trimmedValue;
      if (!this.el.hasClass('editing')) {
        return;
      }
      this.el.removeClass('editing');
      if (trimmedValue = this.input.val().trim()) {
        return this.title = trimmedValue;
      }
    };

    Todo.prototype.render = function() {
      var self;
      self = this;
      return [
        'li', {
          afterRender: function(el) {
            return self.el = $(el);
          }
        }, [
          '.view', {
            dblclick: function() {
              self.el.addClass('editing');
              return self.input.focus();
            }
          }, [
            'input.toggle', {
              type: 'checkbox'
            }, this.completed ? {
              checked: 'checked'
            } : void 0, {
              click: function() {
                return self.completed = !self.completed;
              }
            }
          ], ['label', this.title], [
            'button.destroy', {
              click: function() {
                return self.parent.splice(self.parent.indexOf(self), 1);
              }
            }
          ]
        ], [
          'input.edit', {
            afterRender: function(el) {
              return self.input = $(el);
            },
            type: 'text',
            keypress: function(e) {
              if (e.which === ENTER_KEY) {
                return self.close();
              }
            },
            keydown: function(e) {
              if (e.which === ESC_KEY) {
                return self.el.removeClass('editing');
              }
            },
            blur: function() {
              return self.close();
            }
          }
        ]
      ];
    };

    return Todo;

  })();

}).call(this);
