// Generated by CoffeeScript 1.7.1
(function() {
  var VERSION,
    __slice = [].slice;

  VERSION = '0.1.0';

  this.Busbup = (function() {
    var callbacks, instance;

    function Busbup() {}

    callbacks = {};

    Busbup.prototype.version = VERSION;

    Busbup.prototype.subscribe = function(event, callback) {
      if (callbacks.hasOwnProperty(event)) {
        return callbacks[event].push(callback);
      } else {
        return callbacks[event] = [callback];
      }
    };

    Busbup.prototype.publish = function() {
      var args, callback, event, i, myCallbacks, _i, _j, _len, _results;
      event = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      myCallbacks = callbacks[event];
      if (myCallbacks && myCallbacks.length > 0) {
        for (i = _i = myCallbacks.length - 1; _i >= 0; i = _i += -1) {
          callback = myCallbacks[i];
          if (callback.removeIf && callback.removeIf()) {
            myCallbacks.splice(i, 1);
          }
        }
        if (myCallbacks.length > 0) {
          _results = [];
          for (_j = 0, _len = myCallbacks.length; _j < _len; _j++) {
            callback = myCallbacks[_j];
            _results.push(callback.apply(null, [event].concat(__slice.call(args))));
          }
          return _results;
        } else {
          return delete callbacks[event];
        }
      }
    };

    Busbup.prototype.unsubscribe = function(event, callback) {
      var index;
      if (callbacks[event]) {
        index = callbacks[event].indexOf(callback);
        if (index >= 0) {
          callbacks[event].splice(index, 1);
        }
        if (callbacks[event].length === 0) {
          return delete callbacks[event];
        }
      }
    };

    instance = new Busbup;

    Busbup.subscribe = instance.subscribe;

    Busbup.publish = instance.publish;

    Busbup.unsubscribe = instance.unsubscribe;

    return Busbup;

  })();

}).call(this);
