// Generated by CoffeeScript 1.7.1
(function() {
  this.Collection = (function() {
    var method, methods, _i, _len;

    function Collection() {
      var item, _i, _len;
      this._data = [];
      for (_i = 0, _len = arguments.length; _i < _len; _i++) {
        item = arguments[_i];
        this._data.push(item);
      }
    }

    Collection.prototype.length = function() {
      return this._data.length;
    };

    methods = Object.getOwnPropertyNames(Array.prototype);

    for (_i = 0, _len = methods.length; _i < _len; _i++) {
      method = methods[_i];
      if (['constructor', 'length'].indexOf(method) < 0) {
        Collection.prototype[method] = function() {
          return Array.prototype[method].apply(this._data, arguments);
        };
      }
    }

    return Collection;

  })();

}).call(this);
