// Generated by CoffeeScript 1.7.1
(function() {
  this.Todo = (function() {
    function Todo(parent, title, completed) {
      this.parent = parent;
      this.title = title;
      this.completed = completed != null ? completed : false;
      Busbup.create(this);
      watch(this, ['title', 'completed'], (function(_this) {
        return function() {
          _this.publish(TODO_CHANGED);
          return _this.parent.publish(TODOS_CHANGED);
        };
      })(this));
    }

    return Todo;

  })();

}).call(this);
