// Generated by CoffeeScript 1.7.1
(function() {
  var getTodos, isValidFilter, router, showTodos, todos, todosView;

  todos = void 0;

  getTodos = function() {
    if (todos) {
      return todos;
    } else {
      todos = FreeMart.request('todos:load', 'todos');
      todos.subscribe(CHANGED, function() {
        return FreeMart.request('todos:save', 'todos', todos);
      });
      return todos;
    }
  };

  todosView = void 0;

  showTodos = function(todos, filter) {
    if (todosView) {
      return Busbup.publish(FILTER, filter);
    } else {
      todosView = new TodosView(todos, filter);
      return todosView.render({
        inside: '#todoapp'
      });
    }
  };

  isValidFilter = function(filter) {
    return ['all', 'active', 'completed'].indexOf(filter) >= 0;
  };

  FreeMart.register('/', function() {
    return showTodos(getTodos(), 'all');
  });

  FreeMart.register('/:filter', function(_, filter) {
    if (isValidFilter(filter)) {
      return showTodos(getTodos(), filter);
    } else {
      return console.log("Filter is not supported: '" + filter + "'");
    }
  });

  FreeMart.register(/\/.*/, function(options) {
    var result;
    console.log("Before " + options.$key);
    result = FreeMart.request.apply(FreeMart, arguments);
    console.log(" After " + options.$key);
    return result;
  });

  router = new routes();

  router.get('/', function() {
    return FreeMart.request('/');
  });

  router.get('/:filter', function(req) {
    return FreeMart.request('/:filter', req.params.filter);
  });

  if (location.hash === "") {
    FreeMart.request('/');
  }

}).call(this);
