// Generated by CoffeeScript 1.7.1
(function() {
  var todosView;

  this.todos = FreeMart.request('todos:load', 'todos');

  todos.subscribe(CHANGED, function() {
    return FreeMart.request('todos:save', 'todos', todos);
  });

  todosView = new TodosView(todos);

  todosView.render({
    inside: '#todoapp'
  });

}).call(this);
