// Generated by CoffeeScript 1.7.1
(function() {
  var filterBy, loadTodos, router, showTodos, todosView;

  this.filter = 'all';

  filterBy = function(_filter) {
    if (['all', 'active', 'completed'].indexOf(_filter) < 0) {
      return console.log("Filter is not supported: '" + _filter + "'");
    } else {
      this.filter = _filter;
      return Busbup.publish(FILTER, this.filter);
    }
  };

  loadTodos = function() {
    var todos;
    todos = FreeMart.request('todos:load', 'todos');
    todos.subscribe(CHANGED, function() {
      return FreeMart.request('todos:save', 'todos', todos);
    });
    return todos;
  };

  todosView = void 0;

  showTodos = function() {
    if (!todosView) {
      todosView = new TodosView(loadTodos());
      return todosView.render({
        inside: '#todoapp'
      });
    }
  };

  FreeMart.register('/', function() {
    filterBy('all');
    return showTodos();
  });

  FreeMart.register('/:filter', function(_, filter) {
    filterBy(filter);
    return showTodos();
  });

  FreeMart.register(/\/.*/, function(options) {
    var result;
    console.log("Before " + options.$key);
    result = FreeMart.request.apply(FreeMart, arguments);
    console.log(" After " + options.$key);
    return result;
  });

  router = new routes();

  router.get('/', function() {
    return FreeMart.request('/');
  });

  router.get('/:filter', function(req) {
    return FreeMart.request('/:filter', req.params.filter);
  });

  if (location.hash === "") {
    FreeMart.request('/');
  }

}).call(this);
