// Generated by CoffeeScript 1.7.1
(function() {
  var run;

  this.ENTER_KEY = 13;

  this.ESC_KEY = 27;

  this.CHANGED = 'changed';

  this.FILTER = 'filter';

  run = function() {
    var func;
    func = arguments[arguments.length - 1];
    return func.apply(func, arguments);
  };

  this.filter = 'all';

  this.filterBy = function(filter) {
    if (['all', 'active', 'completed'].indexOf(filter) < 0) {
      return console.log("Filter is not supported: '" + filter + "'");
    } else {
      this.filter = filter;
      return Busbup.publish(FILTER, filter);
    }
  };

}).call(this);
