// Generated by CoffeeScript 1.7.1
(function() {
  var callbacks,
    __slice = [].slice;

  this.ENTER_KEY = 13;

  this.ESC_KEY = 27;

  this.TODOS_CHANGED = 'todos_changed';

  this.bind = function(el, obj, props, options) {
    var callback, tagName;
    if (options.callback) {
      options.callback(el, obj, properties);
    }
    tagName = $(el).get(0).tagName;
    if (tagName === 'INPUT') {
      $(el).change(function() {
        return obj[props] = $(this).val();
      });
    }
    callback = options.callback || function() {
      if (tagName === 'INPUT') {
        return $(el).val(obj[props]);
      } else {
        return $(el).text(obj[props]);
      }
    };
    callback();
    return watch(obj, props, callback, 1);
  };

  callbacks = {};

  this.subscribe = function(event, callback) {
    if (callbacks.hasOwnProperty(event)) {
      return callbacks[event].push(callback);
    } else {
      return callbacks[event] = [callback];
    }
  };

  this.unsubscribe = function(event, callback) {
    var index;
    if (callbacks[event]) {
      index = callbacks[event].indexOf(callback);
      if (index >= 0) {
        callbacks[event].splice(index, 1);
      }
      if (callbacks[event].length === 0) {
        return delete callbacks[event];
      }
    }
  };

  this.publish = function() {
    var args, callback, event, i, myCallbacks, _i, _j, _len, _results;
    event = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    myCallbacks = callbacks[event];
    if (myCallbacks && myCallbacks.length > 0) {
      for (i = _i = myCallbacks.length - 1; _i >= 0; i = _i += -1) {
        callback = myCallbacks[i];
        if (callback.removeIf && callback.removeIf()) {
          myCallbacks.splice(i, 1);
        }
      }
      if (myCallbacks.length > 0) {
        _results = [];
        for (_j = 0, _len = myCallbacks.length; _j < _len; _j++) {
          callback = myCallbacks[_j];
          _results.push(callback.apply(null, [event].concat(__slice.call(args))));
        }
        return _results;
      } else {
        return delete callbacks[event];
      }
    }
  };

}).call(this);
