// Generated by CoffeeScript 1.7.1
(function() {
  this.TodosResource = (function() {
    var deserialize, serialize;

    function TodosResource() {}

    serialize = function(todos) {
      var data, item, _i, _len, _ref;
      data = [];
      _ref = todos._data;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        data.push({
          title: item.title,
          completed: item.completed
        });
      }
      return JSON.stringify(data);
    };

    deserialize = function(str) {
      var data, item, result, _i, _len;
      result = new Todos;
      if (str && (data = JSON.parse(str))) {
        for (_i = 0, _len = data.length; _i < _len; _i++) {
          item = data[_i];
          result._data.push(new Todo(result, item.title, item.completed));
        }
      }
      return result;
    };

    TodosResource.load = function(id) {
      return deserialize(localStorage.getItem(id));
    };

    TodosResource.save = function(id, todos) {
      return localStorage.setItem(id, serialize(todos));
    };

    return TodosResource;

  })();

  FreeMart.register('todos:load', function(_, id) {
    return TodosResource.load(id);
  });

  FreeMart.register('todos:save', function(_, id, todos) {
    return TodosResource.save(id, todos);
  });

}).call(this);
